# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171028_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
