# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171028_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(max_length=50),
        ),
    ]
