# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_userprofile_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
