# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20171105_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 20, 13, 41, 919422)),
        ),
    ]
