# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 16:51
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_assessment_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 8, 17, 51, 25, 19235)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
