# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180108_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 8, 17, 57, 49, 209549)),
        ),
    ]
