# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180108_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 15, 44, 23, 6076)),
        ),
    ]
