# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180109_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 20, 31, 26, 525154)),
        ),
    ]
