# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180112_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 19, 27, 59, 153855)),
        ),
    ]
