# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 18:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0020_auto_20180112_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='assessment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 19, 12, 56, 652443)),
        ),
    ]
