# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20180115_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbours',
            name='idUser',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='neighbours',
            name='sim',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 17, 15, 28, 21, 344667)),
        ),
    ]
