# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 14:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20180117_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 17, 15, 36, 38, 608244)),
        ),
        migrations.AlterField(
            model_name='neighbours',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
