# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20180212_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 18, 59, 33, 296699)),
        ),
        migrations.AlterField(
            model_name='controlpanel',
            name='threshold',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
